### ISSUE TITLE
Memory leak for data insert daemon

### ISSUE THREAD

**Issue by poundifdef** [scratchdata/ScratchDB#10]
There is a memory leak somewhere when consuming messages from the queue and inserting to the DB. Memory should basically be constant (proportional to the number of worker threads.)

**Comment by chumaumenze** [comment]
There are three allocations that consume the most memory.

The first is line 162 in `scratchdb/importer.(*Importer).getColumnsLocal`:
https://github.com/scratchdata/ScratchDB/blob/f742da2ab7b27623ac082043422b9642cd9aea3c/importer/importer.go#L160-L163

Line 303 in `scratchdb/importer.(*Importer).insertDataLocal`
https://github.com/scratchdata/ScratchDB/blob/f742da2ab7b27623ac082043422b9642cd9aea3c/importer/importer.go#L301-L304

Line 450 in `scratchdb/importer.(*Importer).consumeMessages`
https://github.com/scratchdata/ScratchDB/blob/f742da2ab7b27623ac082043422b9642cd9aea3c/importer/importer.go#L450-L454

---

The first two explicit as the function makes a memory allocation of 100 megabytes. The heap growth problem stems from the third function `consumeMessages`.

![Screenshot from 2023-10-11 04-08-16](https://github.com/scratchdata/ScratchDB/assets/20656657/cad02888-a21e-443c-8684-a043d14622a2)

For every new message, a new connection is created and new allocations are made and each new connection is not released after use. This results causes continuous memory leakage which grows as the number of workers and goroutines grows.

I opened PR #23 to fix this.
