### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by PlkMarudny** [scratchdata/ScratchDB#43]
After inserting a record, quering ```my_table``` produces an error: 
```
127.0.0.1 | GET     | /query           | Code: 60. DB::Exception: Table default.my_table does not exist. (UNKNOWN_TABLE) (version 23.10.1.1976 (official build))
```

**Comment by poundifdef** [comment]
Are you running both the `ingest` and `insert` daemon? You should see logs for `insert` where the data is being picked up from the queue and inserted to the DB. Can you share those?

**Comment by poundifdef** [comment]
Hi - I made a fix to the local config, please try it again! https://github.com/scratchdata/ScratchDB/commit/c144b267e7f20b952ed3e0e9fb592681f771fef8

**Comment by PlkMarudny** [comment]
It is working indeed, thank you.
