### ISSUE TITLE
Run Example Error: DB::Exception: Database scratch does not exist. Maybe you meant scratchdb

### ISSUE THREAD

**Issue by ilovewuyi** [scratchdata/ScratchDB#46]
curl -H 'X-Api-Key: local' "http://localhost:3000/query?q=select%20*%20from%20my_table"
Code: 81. DB::Exception: Database scratch does not exist. Maybe you meant scratchdb?. (UNKNOWN_DATABASE) (version 23.10.1.1976 (official build))

**Comment by poundifdef** [comment]
Thanks for reporting - just merged a fix
