### ISSUE TITLE
Have separate "admin" vs individual users

### ISSUE THREAD

**Issue by poundifdef** [scratchdata/ScratchDB#9]
When a user does any query via HTTP, it should use their own DB credentials with limits. Admin tasks performed by the service itself with a more privileged clickhouse user

**Comment by NortySpock** [comment]
You may wish to consider the following user stories:

Some users may only be allowed to contribute to some tables, but not others

Some groups with permissions may encompass multiple users

For the "overkill" solution, full role-based access control will collect users into groups, collect individual permissions (to write to a table) to a role, and then map any number of groups to any number of roles.

**Comment by poundifdef** [comment]
Thanks! This was closed with #32. Certainly more room for improvement here but we can tackle that in a different more specific ticket.
